# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/adrien/Documents/Polytechnique Montréal/Cours/Hiver 2016/INF8801/Projet/object_repositioning"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/adrien/Documents/Polytechnique Montréal/Cours/Hiver 2016/INF8801/Projet/object_repositioning"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/adrien/Documents/Polytechnique Montréal/Cours/Hiver 2016/INF8801/Projet/object_repositioning/CMakeFiles" "/home/adrien/Documents/Polytechnique Montréal/Cours/Hiver 2016/INF8801/Projet/object_repositioning/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/adrien/Documents/Polytechnique Montréal/Cours/Hiver 2016/INF8801/Projet/object_repositioning/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named object_repositioning

# Build rule for target.
object_repositioning: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 object_repositioning
.PHONY : object_repositioning

# fast build rule for target.
object_repositioning/fast:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/build
.PHONY : object_repositioning/fast

src/BoundingBox.o: src/BoundingBox.cpp.o

.PHONY : src/BoundingBox.o

# target to build an object file
src/BoundingBox.cpp.o:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/BoundingBox.cpp.o
.PHONY : src/BoundingBox.cpp.o

src/BoundingBox.i: src/BoundingBox.cpp.i

.PHONY : src/BoundingBox.i

# target to preprocess a source file
src/BoundingBox.cpp.i:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/BoundingBox.cpp.i
.PHONY : src/BoundingBox.cpp.i

src/BoundingBox.s: src/BoundingBox.cpp.s

.PHONY : src/BoundingBox.s

# target to generate assembly for a file
src/BoundingBox.cpp.s:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/BoundingBox.cpp.s
.PHONY : src/BoundingBox.cpp.s

src/Color.o: src/Color.cpp.o

.PHONY : src/Color.o

# target to build an object file
src/Color.cpp.o:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/Color.cpp.o
.PHONY : src/Color.cpp.o

src/Color.i: src/Color.cpp.i

.PHONY : src/Color.i

# target to preprocess a source file
src/Color.cpp.i:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/Color.cpp.i
.PHONY : src/Color.cpp.i

src/Color.s: src/Color.cpp.s

.PHONY : src/Color.s

# target to generate assembly for a file
src/Color.cpp.s:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/Color.cpp.s
.PHONY : src/Color.cpp.s

src/GMM.o: src/GMM.cpp.o

.PHONY : src/GMM.o

# target to build an object file
src/GMM.cpp.o:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/GMM.cpp.o
.PHONY : src/GMM.cpp.o

src/GMM.i: src/GMM.cpp.i

.PHONY : src/GMM.i

# target to preprocess a source file
src/GMM.cpp.i:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/GMM.cpp.i
.PHONY : src/GMM.cpp.i

src/GMM.s: src/GMM.cpp.s

.PHONY : src/GMM.s

# target to generate assembly for a file
src/GMM.cpp.s:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/GMM.cpp.s
.PHONY : src/GMM.cpp.s

src/MeanShift.o: src/MeanShift.cpp.o

.PHONY : src/MeanShift.o

# target to build an object file
src/MeanShift.cpp.o:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/MeanShift.cpp.o
.PHONY : src/MeanShift.cpp.o

src/MeanShift.i: src/MeanShift.cpp.i

.PHONY : src/MeanShift.i

# target to preprocess a source file
src/MeanShift.cpp.i:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/MeanShift.cpp.i
.PHONY : src/MeanShift.cpp.i

src/MeanShift.s: src/MeanShift.cpp.s

.PHONY : src/MeanShift.s

# target to generate assembly for a file
src/MeanShift.cpp.s:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/MeanShift.cpp.s
.PHONY : src/MeanShift.cpp.s

src/Superpixel.o: src/Superpixel.cpp.o

.PHONY : src/Superpixel.o

# target to build an object file
src/Superpixel.cpp.o:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/Superpixel.cpp.o
.PHONY : src/Superpixel.cpp.o

src/Superpixel.i: src/Superpixel.cpp.i

.PHONY : src/Superpixel.i

# target to preprocess a source file
src/Superpixel.cpp.i:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/Superpixel.cpp.i
.PHONY : src/Superpixel.cpp.i

src/Superpixel.s: src/Superpixel.cpp.s

.PHONY : src/Superpixel.s

# target to generate assembly for a file
src/Superpixel.cpp.s:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/Superpixel.cpp.s
.PHONY : src/Superpixel.cpp.s

src/foreground_extraction.o: src/foreground_extraction.cpp.o

.PHONY : src/foreground_extraction.o

# target to build an object file
src/foreground_extraction.cpp.o:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/foreground_extraction.cpp.o
.PHONY : src/foreground_extraction.cpp.o

src/foreground_extraction.i: src/foreground_extraction.cpp.i

.PHONY : src/foreground_extraction.i

# target to preprocess a source file
src/foreground_extraction.cpp.i:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/foreground_extraction.cpp.i
.PHONY : src/foreground_extraction.cpp.i

src/foreground_extraction.s: src/foreground_extraction.cpp.s

.PHONY : src/foreground_extraction.s

# target to generate assembly for a file
src/foreground_extraction.cpp.s:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/foreground_extraction.cpp.s
.PHONY : src/foreground_extraction.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/opencv_2_sdl.o: src/opencv_2_sdl.cpp.o

.PHONY : src/opencv_2_sdl.o

# target to build an object file
src/opencv_2_sdl.cpp.o:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/opencv_2_sdl.cpp.o
.PHONY : src/opencv_2_sdl.cpp.o

src/opencv_2_sdl.i: src/opencv_2_sdl.cpp.i

.PHONY : src/opencv_2_sdl.i

# target to preprocess a source file
src/opencv_2_sdl.cpp.i:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/opencv_2_sdl.cpp.i
.PHONY : src/opencv_2_sdl.cpp.i

src/opencv_2_sdl.s: src/opencv_2_sdl.cpp.s

.PHONY : src/opencv_2_sdl.s

# target to generate assembly for a file
src/opencv_2_sdl.cpp.s:
	$(MAKE) -f CMakeFiles/object_repositioning.dir/build.make CMakeFiles/object_repositioning.dir/src/opencv_2_sdl.cpp.s
.PHONY : src/opencv_2_sdl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... object_repositioning"
	@echo "... src/BoundingBox.o"
	@echo "... src/BoundingBox.i"
	@echo "... src/BoundingBox.s"
	@echo "... src/Color.o"
	@echo "... src/Color.i"
	@echo "... src/Color.s"
	@echo "... src/GMM.o"
	@echo "... src/GMM.i"
	@echo "... src/GMM.s"
	@echo "... src/MeanShift.o"
	@echo "... src/MeanShift.i"
	@echo "... src/MeanShift.s"
	@echo "... src/Superpixel.o"
	@echo "... src/Superpixel.i"
	@echo "... src/Superpixel.s"
	@echo "... src/foreground_extraction.o"
	@echo "... src/foreground_extraction.i"
	@echo "... src/foreground_extraction.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/opencv_2_sdl.o"
	@echo "... src/opencv_2_sdl.i"
	@echo "... src/opencv_2_sdl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

